from typing import Match
from typing import List

def check_prefix(custom_str: str) -> bool: ...
def check_suffix(custom_str: str) -> bool: ...
def flag_regional_indicator(code: List[str]) -> str: ...
def flag_tag_sequence(code: List[str]) -> str: ...
class Flag:
    def __init__(self, prefix_str: str, suffix_str: str, warn: bool) -> None: ...
    @staticmethod
    def flag(countrycode: str) -> str: ...
    def flagize(self, text: str, subregions: bool) -> str: ...
    def dflagize(self, text: str, subregions: bool) -> str: ...
    def flagize_subregional(self, text: str) -> str: ...
    def dflagize_subregional(self, text: str) -> str: ...
def flag(countrycode: str) -> str: ...
def flagize(text: str, subregions: bool) -> str: ...
def dflagize(text: str, subregions: bool) -> str: ...
def flagize_subregional(text: str) -> str: ...
def dflagize_subregional(text: str) -> str: ...
