name: Upload Python Package to PyPi.org

on:
  release:
    types: [published]

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2
        with:
          attest-build-provenance-github: 'true'

  deploy:
    name: Publish to pypi.org
    environment:
      name: pypi
      url: https://pypi.org/p/emoji-country-flag
    runs-on: ubuntu-latest
    needs: build-package
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Download package built by build-and-inspect-python-package
        uses: actions/download-artifact@v5
        with:
          name: Packages
          path: dist
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
